all: server.c client.c server367.c client367.c server-test.c client-test.c
	gcc -o server server.c
	gcc -o client client.c
	gcc -o server367 server367.c
	gcc -o client367 client367.c
	gcc -o sTest server-test.c
	gcc -o cTest client-test.c
clean:
	rm server client
